README.md

- signed-off-by: Kyle Birkeland <kylebirkeland@gmail.com>

added atop

---

README.md

Added Lynx to Network Chapter

---

README.md

[tldr](https://github.com/tldr-pages/tldr) is a useful tool I find myself referring to occasionally for those tools you can't always remember such as the following examples:
```
╰─➤  tldr grep
grep
Matches patterns in input text.
Supports simple patterns and regular expressions.
- Search for an exact string:
grep search_string path/to/file
- Search in case-insensitive mode:
grep -i search_string path/to/file
- Search recursively (ignoring non-text files) in current directory for an exact string:
grep -RI search_string .
- Use extended regular expressions (supporting `?`, `+`, `{}`, `()` and `|`):
grep -E ^regex$ path/to/file
- Print 3 lines of [C]ontext around, [B]efore, or [A]fter each match:
grep -C|B|A 3 search_string path/to/file
- Print file name with the corresponding line number …
```

Adding tldr

---

README.md

- signed-off-by: Max Al Farakh <maxt3r@gmail.com>

Added SSL Check to the list

---

README.md

I switched from sublime to vscode and really like maybe its worth adding i dont know. thanks! great list!

added vscode to text editors

---

README.md

SSH to host without processing user environment scripts.

Added `ssh -tt` 

---

README.md

Add link to Linux Guide and Hints

---

README.md

Test if the current user is sudo-su'd into this session

---

README.md

Added [CodeSandbox.io](https://codesandbox.io/) under the Code parsers heading. 
Also reworded descriptions of _Shodan 2000_ and _PentestIt_ so that it did not overflow to the next line.

Added CodeSandbox

---

README.md

Fix socat URL

---

README.md

Added description for lnav logging tool

Added lnav entry

---

README.md

- signed-off-by: Wojciech Sciesinski <wojciech@sciesinski.net>

Add Shell Style Guide

---

README.md

- signed-off-by: Wojciech Sciesinski <wojciech@sciesinski.net>

Add Performance Co-Pilot

---

README.md

Shaved a few pipes out of a netstat example with awk split and pattern matching

Minor awk tweak

---

README.md

Hi in my humble opinion websploit is a valuable addition to the list. The project combines different vulnerable webapps in one vm in different docker instances. I am not sure about the description of the bounty platforms. Say something and i change them.

Added Websploit and a few Bounty platforms

---

README.md

Since you have already my guide for DNS-over-HTTPS, better add the next step with DNS-over-TLS that is quite useful with Android 9 (Pie).

Add tutorial to setup a DNS-over-TLS server

---

README.md

Edited Grammar and Fixed various descriptions.

Universalized Grammar and Fixed Descriptions in README.md

---

README.md

As similar to my previous pull request, I have fixed grammar in description of various tools.

Fixed Grammar for various tool

---

README.md

Add pentoo to operating systems. Commit messages mistakenly state gentoo.

Add pentoo to operating systems

---

README.md

Added dnsdbq API client

---

README.md

Fix typo curiousity to curiosity

---

README.md

This PR proposes `tclsh` - very powerful, cross-platform extendable shell with sane quoting rules, controlled arguments expanding rules and more consistent and well thought out syntax, with huge functionality and wide range of libraries...
About comparison with *sh (here bash) - https://www.slant.co/versus/1601/5079/~bash_vs_tcl

add 'tclsh' - most powerful cross-platform shell ever

---

README.md

Add Irssi under Messenger/IRC Clients

---

README.md

Add pythoncheatsheet.org website:
"Anyone can forget how to make character classes for a Regex, slice a List or do a For loop. This cheat sheet tries to provide a basic reference for beginner and advanced developers, lower the entry barrier for newcomers and help veterans refresh the old tricks."

add pythoncheatsheet.org

---

README.md

extendsclass provides an online HTTP client and also other tools (Regex tester, XPath tester, SQLite browser, ...)

Added extendsclass, an online HTTP client, to 'Net-tools' chapter

---

README.md

Added another IRC chat client to the list. It's nice to provide multiple options, especially good ones!

Add WeeChat

---

README.md

Fixes https://github.com/trimstray/the-book-of-secret-knowledge/issues/134

fix: #134 Overthewire duplicate issue

---

README.md

I really like using `ncdu`. It is a very easy to use interface on top of `du` and it makes finding and managing space hogs on a *nix system much, much easier.

Added ncdu to file utilities

---

README.md

both are designed for SSH sessions over a poor internet connection.
- signed-off-by: Sebi <sebi@tuximail.de>

Added 'mosh' and 'et' as SSH alternatives

---

README.md

Add SpaceVim a community-driven vim distribution similar to Spacemacs.

Add SpaceVim

---

README.md

I have added new entry **cheat.sh** in All-in-One section.

cheat.sh added in All-in-one Section

---

README.md

A curated list of all machine learning algorithms and deep learning algorithms grouped by category.

Added machine-learning-algorithms

---

README.md

* Add link to Awesome-ZSH-plugins list
* Removed a few trailing spaces while I was editing to make entries consistent

Add link to Awesome ZSH plugins list

---

README.md

Alacritty is A fast, cross-platform, OpenGL terminal emulator

add Alacritty

---

README.md

This deletes a URL that redirects to malware.
Regarding the "Signature of commit" requirement in CONTRIBUTING, I think that is intended for the person doing the merge instead of the person issuing the pull request. If I have that wrong just LMK. 
(A more detailed clue about the intended modification to .git/hooks/prepare-commit-msg is welcome though not strictly necessary).
If I'm doing this right, I'm happy to do a pass on curating and tidying up links.

Delete fakeface - fixes #216

---

README.md

Added Cutter to Pentest tools, and added Socat to network tools.

Add Socat and Cutter

---

README.md

The original link seems to be dead, reverting to wayback machine

Update README.md, dead link

---

README.md

Can detect typosquatters, phishing attacks, fraud, and brand impersonation
https://github.com/elceef/dnstwist

Added dnstwist

---

README.md

- signed-off-by: crypt0rr <57799908+crypt0rr@users.noreply.github.com>

Added ssl-cert-check
